import type { CapacitorConfig } from '@capacitor/cli';

// BigData for Android + iOS. The web payload in www/ is generated by scripts/build-payload.mjs (never
// hand-edited) and served from the platform's local scheme: capacitor://localhost on iOS (the
// hostname keeps secure-context APIs such as crypto.subtle available) and https://localhost on Android.
const config: CapacitorConfig = {
  appId: 'com.alldatalogs.bigdata',
  appName: 'BigData',
  webDir: 'www',
  android: {
    // Internal-track debugging builds only: chrome://inspect over USB. Off for store builds.
    webContentsDebuggingEnabled: process.env.BIGDATA_DEBUG_WEBVIEW === '1',
  },
  ios: {
    contentInset: 'never',
  },
  plugins: {
    SplashScreen: { launchAutoHide: true, backgroundColor: '#0a0a0d' },
  },
};

export default config;
